In [28]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [29]:
import numpy as np

In [30]:
# array 생성
arr_1 = np.arange(1000)

In [31]:
type(arr_1)

numpy.ndarray

In [32]:
arr_1

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [33]:
# array 를 list로 변경 가능
arr2list = list(arr_1)

In [34]:
type(arr2list)

list

In [35]:
list_2 = [i for i in range(0,50)]

In [36]:
arr_2 = np.array(list_2)

In [37]:
type(arr_2)

numpy.ndarray

In [38]:
list_3 = ["1", "2", "3"]

In [39]:
arr_3 = np.array(list_3)

In [40]:
arr_3

array(['1', '2', '3'], dtype='<U1')

In [41]:
arr_2*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [42]:
# 문자가 섞여있으면 연산이 동작하지 않는다. 
# arr_3 + 2

In [43]:
my_arr = np.arange(1000000)

In [44]:
my_list = list(np.arange(1000000))

In [45]:
%time for _ in range(100): my_arr2 = my_arr*2

CPU times: user 127 ms, sys: 10.5 ms, total: 138 ms
Wall time: 140 ms


In [46]:
%time for _ in range(100): my_list2 = [ i*2 for i in my_list ]

CPU times: user 22.6 s, sys: 1.39 s, total: 24 s
Wall time: 24.7 s


In [47]:

# m2 16 512 -> 200
# m1pro 16 512 -> 230

In [48]:
# array 생성
data_1 = [6,7,8,9,2]

In [49]:
type(data_1)

list

In [50]:
arr_1 = np.array(data_1)

In [51]:
arr_1.ndim

1

In [52]:
data_2 = [1,2]

In [53]:
arr_2 = np.array(data_2)

In [54]:
arr_2#vector

array([1, 2])

In [55]:
arr_2.ndim

1

In [56]:
data_3 = [1,2,3]

In [57]:
arr_3 = np.array(data_3)

In [58]:
arr_3.ndim

1

In [59]:
data_4 = [4,5,6]

In [60]:
arr_4 = np.array(data_4)

In [61]:
data_5 = [data_3, data_4]

In [62]:
arr_5 = np.array(data_5)

In [63]:
arr_5#matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
arr_5.ndim

2

In [65]:
data_6 = [[[1, 2, 3],[4, 5, 6]],[[7, 8, 9],[10, 11, 12]]]

In [66]:
arr_6 = np.array(data_6)

In [67]:
arr_6.ndim

3

In [68]:
arr_6

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [69]:
# 참고
# np.mat 이라는 함수를 통해 matrix 를 생성할수 있지만 생성하지 않는다. 

In [70]:
# 빈 리스트 = []
# 숫자 초기화 = 0 또는 1로 초기화
# np.random.randn # 추정이나 예측하기 위해서 초기값으로 지정할때 

In [71]:
np.random.randn(1,5)

array([[-1.29977679, -0.77181078,  0.82339759,  1.60658084,  0.20655255]])

In [72]:
np.random.randn(3,5)

array([[ 1.93987574,  0.28893518, -0.20520683,  0.03306152, -0.20877107],
       [-0.39325844, -1.53955083, -0.00461921,  0.83347328,  0.61774072],
       [-1.73406868,  1.14746396,  1.45595182, -0.66269548, -0.2383351 ]])

In [73]:
np.random.randn(3,5,6)

array([[[-0.71965172,  0.2016997 ,  3.06529931, -1.45372313,
          0.25092692, -1.05020622],
        [ 0.15134059,  0.6886955 , -2.01347095, -2.00705163,
         -0.43120444, -0.0834687 ],
        [-0.56809675,  0.67794331, -1.50699137, -0.11113039,
          0.97549926,  0.31590791],
        [-1.21559407, -0.60070398,  1.06539823,  0.7854262 ,
         -0.28758394, -1.37986321],
        [ 0.07856767, -0.68640799, -0.46462248,  2.05762835,
          0.35489105, -1.42282051]],

       [[-1.83449214, -0.44055753, -0.54396514,  0.62836975,
         -0.82351405, -0.40629253],
        [ 0.92350539, -0.38014093,  1.11004926, -0.356961  ,
         -0.36025628, -1.32103242],
        [ 1.36718653,  1.87140538,  0.81899778, -2.07299955,
         -0.80454689, -1.10774291],
        [-0.45933887, -0.93777649,  1.06443492, -1.29550167,
          1.85905367,  0.12992652],
        [ 0.1500851 ,  0.3182749 , -0.17247098,  0.14340243,
         -1.11338185, -1.09528712]],

       [[ 1.78326627,  0.5

In [74]:
arr_7 = np.zeros(10)

In [75]:
arr_7

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [76]:
arr_8 = np.zeros((10,10))

In [77]:
arr_8 # 10x10인 값이 0으로 채워진 행렬이 생성된다.

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [78]:
arr_9 = np.zeros((10,10,3))

In [79]:
arr_9

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
  

In [80]:
arr_9.shape

(10, 10, 3)

In [81]:
arr_7.shape

(10,)

In [82]:
arr_6.shape

(2, 2, 3)

In [83]:
arr_10 = np.empty((3,4))

In [84]:
arr_11 = np.empty((3,5))

In [85]:
arr_10

array([[1.9367579e-316, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000]])

In [86]:
arr_11

array([[1.93987574, 0.28893518, 0.20520683, 0.03306152, 0.20877107],
       [0.39325844, 1.53955083, 0.00461921, 0.83347328, 0.61774072],
       [1.73406868, 1.14746396, 1.45595182, 0.66269548, 0.2383351 ]])

In [87]:
np.full((3,4), 0)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [88]:
np.full((3,4), 1)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [89]:
np.full((3,4), 2)

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [90]:
# numpy 배열의 산술 연산
# numpy 배열은 반복문을 작성하지 않고 데이터를 일괄 처리할수 있다.
# 이를 벡터화 기능이라고 한다.

In [91]:
arr_1 = np.array([[1,2,3],[4,5,6]])

In [92]:
# 요소곱
arr_1 * arr_1

array([[ 1,  4,  9],
       [16, 25, 36]])

In [93]:
# 덧셈, 뺄셈
arr_1 + arr_1

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [94]:
# 나눗셈
arr_1/arr_1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [95]:
# 비교연산자 사용가능
arr_1 >= arr_1

array([[ True,  True,  True],
       [ True,  True,  True]])

In [96]:
# 행렬곱 
arr_2 = np.array([[1,2,3],[4,5,6]])
arr_3 = np.array([[7,10],[8,11],[9,12]])

In [97]:
np.dot(arr_2,arr_3) # 행렬 곱셈을 위한 연산dot

array([[ 50,  68],
       [122, 167]])

In [98]:
# 색인과 슬라이싱
# 리스트와 동일

In [99]:
arr_1 = np.arange(10)

In [100]:
arr_1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
arr_1[5]

5

In [102]:
arr_1[5:8]

array([5, 6, 7])

In [103]:
arr_1[-1:]

array([9])

In [105]:
arr_1[-1:]

array([9])

In [106]:
arr_1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16],[17,18,19,20]])

In [107]:
arr_1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [108]:
arr_1.shape

(5, 4)

In [109]:
arr_1[:,-1]

array([ 4,  8, 12, 16, 20])

In [110]:
arr_1[:,-1].shape

(5,)

In [111]:
arr_1[:,-1:].shape

(5, 1)

In [112]:
arr_2 = np.arange(24).reshape(3,2,4) 
#에서 2,6,10,14,18,22 만 뽑아 보세요

In [113]:
arr_2

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [114]:
arr_2.shape

(3, 2, 4)

In [115]:
arr_2[:,:,2]

array([[ 2,  6],
       [10, 14],
       [18, 22]])

In [116]:
arr_2[:,:,[2]]

array([[[ 2],
        [ 6]],

       [[10],
        [14]],

       [[18],
        [22]]])

In [117]:
arr_2[:,:,2:3]

array([[[ 2],
        [ 6]],

       [[10],
        [14]],

       [[18],
        [22]]])

In [118]:
arr_2[:,:,::2]
# 시작:끝:step

array([[[ 0,  2],
        [ 4,  6]],

       [[ 8, 10],
        [12, 14]],

       [[16, 18],
        [20, 22]]])

In [119]:
arr_1 = np.arange(24)

In [120]:
arr_1.shape

(24,)

In [121]:
arr_1_1 = arr_1.reshape(3,2,4) 

In [122]:
arr_2 = np.arange(72)

In [123]:
arr_2_1 = arr_2.reshape(9,8)

In [124]:
arr_2_1.shape

(9, 8)

In [125]:
arr_2_1.reshape(72)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71])

In [126]:
arr_2_2 = arr_2_1.reshape(9,2,-1) #-1 을 통해 마지막 값을 저절로 결정하게 해준다. 

In [127]:
arr_2_2.shape

(9, 2, 4)

In [130]:
arr_3= np.arange(24).reshape(2,3,4)
# 6과 18 만을 array에서 뽑아 보세요.

In [131]:
arr_3[:,[1],[2]]

array([[ 6],
       [18]])

In [132]:
arr_3.shape

(2, 3, 4)

In [133]:
arr_3

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

# 블리언으로 값 선택하기

In [134]:
names = np.array(["오민엽", "윤상원", "이진경", "김예담", "오민엽","서동한","이해규"])

In [135]:
names == "오민엽"

array([ True, False, False, False,  True, False, False])

In [136]:
data = np.random.randn(7,4)

In [137]:
data

array([[ 9.04621688e-01,  4.88891498e-01, -4.57387672e-01,
        -2.84242779e-01],
       [-1.94017179e+00,  9.43282081e-01, -1.50338192e+00,
         1.03828733e-01],
       [-5.26872338e-01, -7.84867288e-01,  9.40286248e-01,
         9.20692056e-01],
       [-2.39479238e-01, -5.69629596e-02,  1.14038555e+00,
        -4.57194643e-02],
       [-1.77664276e+00,  7.20925203e-01,  9.00054502e-01,
        -1.28085761e+00],
       [-2.27301536e+00,  1.35684929e+00, -3.39588424e-01,
         1.73470592e-03],
       [-1.93359589e+00, -6.42842053e-01,  5.24438882e-01,
        -7.99287412e-01]])

In [138]:
data[names == "오민엽"]

array([[ 0.90462169,  0.4888915 , -0.45738767, -0.28424278],
       [-1.77664276,  0.7209252 ,  0.9000545 , -1.28085761]])

In [139]:
bools = names == "오민엽"

In [140]:
data[bools]

array([[ 0.90462169,  0.4888915 , -0.45738767, -0.28424278],
       [-1.77664276,  0.7209252 ,  0.9000545 , -1.28085761]])

In [141]:
# 질문 data array에서 0 보다 큰수만 추출해 보세요 

In [142]:
data[data>0]

array([0.90462169, 0.4888915 , 0.94328208, 0.10382873, 0.94028625,
       0.92069206, 1.14038555, 0.7209252 , 0.9000545 , 1.35684929,
       0.00173471, 0.52443888])

In [143]:
bools = data > 0 

In [144]:
data[bools]

array([0.90462169, 0.4888915 , 0.94328208, 0.10382873, 0.94028625,
       0.92069206, 1.14038555, 0.7209252 , 0.9000545 , 1.35684929,
       0.00173471, 0.52443888])

In [145]:
# 0보다 작은 숫자들은 0으로 치환 하세요 

In [146]:
data[data<0] = 0

In [147]:
data

array([[0.90462169, 0.4888915 , 0.        , 0.        ],
       [0.        , 0.94328208, 0.        , 0.10382873],
       [0.        , 0.        , 0.94028625, 0.92069206],
       [0.        , 0.        , 1.14038555, 0.        ],
       [0.        , 0.7209252 , 0.9000545 , 0.        ],
       [0.        , 1.35684929, 0.        , 0.00173471],
       [0.        , 0.        , 0.52443888, 0.        ]])

In [148]:
# 팬시색인
# - 정수배열로 색인

In [149]:
arr = np.random.randn(8,4)

In [150]:
arr[0] = 0

In [151]:
arr

array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 1.40910545, -1.18351374, -0.5958172 ,  0.64713265],
       [ 0.84641911,  1.58626162,  0.5200283 ,  0.21759346],
       [-1.89137566, -0.75911403,  0.14314283,  2.34076332],
       [-0.01016947, -1.3738604 ,  2.27224478, -1.64693728],
       [ 1.89205782,  0.24812374, -1.27475967, -0.89947578],
       [-1.07138873, -0.32404295, -0.08008491, -0.98586202],
       [-0.89454773, -1.5429069 ,  1.39655908,  0.03185838]])

In [152]:
# 특정한 row를 선택하고 싶으면 원하는순서가 명시된 정수가 담긴 list 또는 array를 넘기면 된다.

In [153]:
arr

array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 1.40910545, -1.18351374, -0.5958172 ,  0.64713265],
       [ 0.84641911,  1.58626162,  0.5200283 ,  0.21759346],
       [-1.89137566, -0.75911403,  0.14314283,  2.34076332],
       [-0.01016947, -1.3738604 ,  2.27224478, -1.64693728],
       [ 1.89205782,  0.24812374, -1.27475967, -0.89947578],
       [-1.07138873, -0.32404295, -0.08008491, -0.98586202],
       [-0.89454773, -1.5429069 ,  1.39655908,  0.03185838]])

In [154]:
arr[[4,3,0]]

array([[-0.01016947, -1.3738604 ,  2.27224478, -1.64693728],
       [-1.89137566, -0.75911403,  0.14314283,  2.34076332],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [155]:
arr = np.arange(32).reshape(8,4)

In [156]:
arr[:,[1,2]]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22],
       [25, 26],
       [29, 30]])

In [157]:
arr[:,[1,2]][:,1]

array([ 2,  6, 10, 14, 18, 22, 26, 30])

In [158]:
# 전치와 축변경
# - 배열의 전치는 데이터의 행과 열을 변경 해준다. 

In [159]:
arr = np.arange(24)

In [160]:
arr.shape

(24,)

In [161]:
arr = arr.reshape(3,8)

In [162]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [163]:
arr.T

array([[ 0,  8, 16],
       [ 1,  9, 17],
       [ 2, 10, 18],
       [ 3, 11, 19],
       [ 4, 12, 20],
       [ 5, 13, 21],
       [ 6, 14, 22],
       [ 7, 15, 23]])

In [164]:
arr.transpose()

array([[ 0,  8, 16],
       [ 1,  9, 17],
       [ 2, 10, 18],
       [ 3, 11, 19],
       [ 4, 12, 20],
       [ 5, 13, 21],
       [ 6, 14, 22],
       [ 7, 15, 23]])

In [165]:
arr_1 = np.arange(8)

In [166]:
arr_1

array([0, 1, 2, 3, 4, 5, 6, 7])

In [167]:
# 벡터 자체로는 전치 되지 않는다. 
arr_1.T

array([0, 1, 2, 3, 4, 5, 6, 7])

In [168]:
arr_1.reshape(1,-1)

array([[0, 1, 2, 3, 4, 5, 6, 7]])

In [169]:
arr_1.reshape(1,-1).shape

(1, 8)

In [170]:
arr_1.reshape(1,-1).T

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [171]:
arr_1.reshape(1,-1).T.shape

(8, 1)

In [172]:
arr = np.random.randn(5,4)

In [173]:
# 평균
arr.mean()

-0.22235532795621138

In [174]:
arr.sum()

-4.447106559124228

In [175]:
# axis = 0 가로 
# axis = 1 세로

In [176]:
arr.shape

(5, 4)

In [177]:
arr

array([[-1.52107274, -1.47296262,  2.25132791,  0.1598451 ],
       [ 0.61238156, -1.60145568, -0.75596172, -0.83685686],
       [ 2.49380155, -1.85532243, -0.80243995, -0.79721061],
       [ 0.48303236, -0.47124222, -0.61276148, -1.06594209],
       [ 1.18581831, -0.22057776, -0.48616264,  0.86665546]])

In [178]:
arr.mean(axis = 0)

array([ 0.65079221, -1.12431214, -0.08119958, -0.3347018 ])

In [179]:
arr.mean(axis = 1)

array([-0.14571559, -0.64547318, -0.24029286, -0.41672836,  0.33643334])

In [180]:
arr.sum(axis = 0)

array([ 3.25396104, -5.62156071, -0.40599788, -1.67350901])

In [181]:
arr.sum(axis = 1)

array([-0.58286236, -2.58189271, -0.96117144, -1.66691343,  1.34573337])

In [182]:
arr_1 = np.arange(10)

In [183]:
arr_1.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [184]:
arr_1 = arr_1.reshape(2,5)

In [185]:
# arr_1.T.mean(axis = 0)
arr_1.mean(axis = 1)

array([2., 7.])

In [186]:
arr_1.mean(axis = 0)

array([2.5, 3.5, 4.5, 5.5, 6.5])

In [187]:
# 블리언 메소드
# 양수인 원소들의 개수
(arr>0).sum()

7

In [188]:
# 정렬 
# sort()

In [189]:
arr_2 = np.random.rand(6)

In [190]:
arr_2.sort()

In [191]:
arr_2

array([0.13700785, 0.44944607, 0.53234431, 0.5843754 , 0.64464337,
       0.66266132])

In [192]:
# https://numpy.org/doc/stable/reference/generated/numpy.sort.html
# 내림차순 오름차순 기능은 따로 없다. 
arr_2.sort()

In [193]:
# 배열 붙이기
# concatenate()
arr_1 = np.array(([11,12,13], [14,15,16]))
arr_2 = np.array(([21,22,23], [24,25,26]))

In [194]:
# 브로드 캐스팅
np.concatenate([arr_1, arr_2], axis =0)

array([[11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

In [195]:
np.concatenate([arr_1, arr_2], axis = 1)

array([[11, 12, 13, 21, 22, 23],
       [14, 15, 16, 24, 25, 26]])

In [196]:
# 브로드 캐스팅
# - 다른모양의 배열간의 산술 연산을 가능해주도록 한다. 

In [197]:
arr_3 = np.arange(12).reshape(4,3)

In [198]:
arr_3

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [199]:
arr_4 = np.array([1,2,3])

In [200]:
arr_4.shape

(3,)

In [201]:
arr_3 + arr_4

array([[ 1,  3,  5],
       [ 4,  6,  8],
       [ 7,  9, 11],
       [10, 12, 14]])

In [202]:
arr_5 = np.array([[1],[2],[3],[4]])

In [203]:
arr_3 + arr_5

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])